# 13.Calculate total booking value generated by every passenger.
SELECT p.passenger_id, p.passenger_name, COALESCE(SUM(b.seats * f.ticket_price), 0) AS total_booking_value
FROM passengers p
LEFT JOIN bookings b ON p.passenger_id = b.passenger_id
LEFT JOIN flights f ON b.flight_id = f.flight_id
GROUP BY p.passenger_id, p.passenger_name;

# 14.Display passengers whose confirmed booking value exceeds ₹10,000.
SELECT p.passenger_id, p.passenger_name, SUM(b.seats * f.ticket_price) AS confirmed_booking_value
FROM bookings b
JOIN passengers p ON b.passenger_id = p.passenger_id
JOIN flights f ON b.flight_id = f.flight_id
WHERE b.status = 'Confirmed'
GROUP BY p.passenger_id, p.passenger_name
HAVING SUM(b.seats * f.ticket_price) > 10000;
